apiVersion: v2
name: loretta-bank
description: Loretta Bank microservices umbrella chart
version: 0.1.0
appVersion: "1.0.0"
type: application

dependencies:
  - name: config
    version: 0.1.0
    condition: config.enabled
  - name: postgres
    version: 0.1.0
    condition: postgres.enabled
  - name: redis
    version: 0.1.0
    condition: redis.enabled
  - name: kafka
    version: 0.1.0
    condition: kafka.enabled
  - name: discovery-service
    version: 0.1.0
  - name: api-gateway
    version: 0.1.0
  - name: auth-service
    version: 0.1.0
  - name: customer-service
    version: 0.1.0
  - name: account-service
    version: 0.1.0
  - name: transaction-service
    version: 0.1.0
  - name: notification-service
    version: 0.1.0
  - name: audit-service
    version: 0.1.0
  - name: reporting-service
    version: 0.1.0
  - name: frontend
    version: 0.1.0
