{{- if not .Values.global.externalSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: loretta-secrets
  labels:
    app.kubernetes.io/part-of: loretta-bank
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.global.postgres.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.global.postgres.password | quote }}
  POSTGRES_DB: loretta_auth
  DB_USERNAME: {{ .Values.global.postgres.username | quote }}
  DB_PASSWORD: {{ .Values.global.postgres.password | quote }}
  JWT_SECRET: {{ .Values.global.jwt.secret | quote }}
  AUTH_BOOTSTRAP_ADMIN_PASSWORD: {{ .Values.global.auth.bootstrapAdminPassword | quote }}
{{- end }}
