apiVersion: v1
kind: ConfigMap
metadata:
  name: loretta-config
data:
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  EUREKA_URL: http://eureka:eureka@discovery-service:8761/eureka/
  CUSTOMER_SERVICE_URL: http://customer-service:8082
  ACCOUNT_SERVICE_URL: http://account-service:8083
  TRANSACTION_SERVICE_URL: http://transaction-service:8084
  AUTH_BOOTSTRAP_ENABLED: "true"
  AUTH_BOOTSTRAP_ADMIN_EMAIL: admin@lorettabank.co.za
