apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: loretta-bank
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres.yaml
  - redis.yaml
  - kafka.yaml
  - discovery-service.yaml
  - api-gateway.yaml
  - auth-service.yaml
  - customer-service.yaml
  - account-service.yaml
  - transaction-service.yaml
  - notification-service.yaml
  - audit-service.yaml
  - reporting-service.yaml
  - frontend.yaml
  - ingress.yaml
