spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/loretta_customer
    username: loretta
    password: loretta_secret
  kafka:
    bootstrap-servers: localhost:9092
eureka:
  client:
    enabled: false
