apiVersion: v1
kind: Service
metadata:
  name: {{ include "account-service.fullname" . }}
  labels:
    {{- include "account-service.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      port: {{ .Values.port }}
      targetPort: http
  selector:
    {{- include "account-service.selectorLabels" . | nindent 4 }}
